= SDE

Стандартная среда разработки - Standard Development Environment

https://github.com/projectd-org/projectd[GitHub] +
https://discord.gg/2PbUG6vUTR[Discord]

== Абстрактно
Процесс разработки проектов сильно поменялся за последние десятилетия.

Инструменты разработчика - не особо.

Надо сделать норм.

Идея такая - инструменты отвязываются от файловой структуры (проекта и системы в целом).

Становятся просто программами, которые на старте получают конфиг (как DI, нhttps://habr.com/ru/top/о на уровне системы в целом).

Затем им приходят файлы, которые они должны обработать согласно этому конфигу.

Для этого используется демон, с которым инструменты общаются через библиотеку SDK для конкретного языка.

Схема данных конфига описывается в терминах языка и переводится в абстрактное описание (условную JSON schema), которым уже пользуется демон.

Демон ведёт себя как мини-ос/шелл, инкапсулируя в себе работу с файлами и композицию утилит.


Весь проект хранится в БД.

Инструменты получают библиотеку-драйвер для работы с ней.

Вьюхи (линзы)

Кор-область и рабочая область

Язык описания структур данных (со всей историей изменений, алиасы, версионность, скрипты миграции)

Нужен быстрый интероп, сильная типизация, отображение в большинство популярных языков, ссылки друг на друга

Декларативность вместо императивности

== Создание проекта

[source]
----
sde init ./project-folder > project.sde
----

Создаст бинарник проекта из существующей папки.
Туда войдут все файлы кроме тех, что находятся в gitignore.

#TODO: инициализация из гит-ветки напрямую#

Все симлинки будут проигнорированы, все файлы будут доступны на запись.
Текстовые файлы будут сохранены как UTF, остальные - как Data.

#TODO: линки#

Создастся вьюха sfs:fs, вомпроизводящая ту же структуру файловой системы.

== Работа

[source]
----
sde fs ./project.sde project --write project-temp.sde
----

Спроецирует project.sde из вьюхи sfs:fs в папку project.

Все изменения в этой папке (кроме gitignore) будут отражаться в project-temp.sde

Оба sde файла будут защищены от записи пока команда работает.

== Фиксация

[source]
----
sde commit project-temp.sde project.sde
----

Все файлы из project-temp.sde будут перенесены в project.sde.

#TODO: удаление temp#

#TODO: сообщение#

#TODO: gitless враппер#

== Конфиг

== Кодген

== Уровни представления

Нижний - capnp

Средний - yaml

Верхний - full-typed yaml со схемой ?
